name: Деплой на стейдж

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Проверка кода
      uses: actions/checkout@v2

    - name: Инсталяция зависимостей и копиляция билда
      run: |
        npm install
        npm run build

    - name: Деплой на сервер
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.DEPLOY_STAGE_SSH_KEY }}
        source: "./build/*"
        target: "/var/www/html/"
