name: Деплой на стейдж

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Удаляем файлы прошлого деплоя
      run: |
       ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} "rm -rf /var/www/html/*"


    - name: Проверка кода
      uses: actions/checkout@v2

    - name: Установка Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Инсталяция зависимостей и копиляция билда
      run: |
        npm install
        npm run build

    - name: Деплой на сервер
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: root
        key: ${{ secrets.DEPLOY_STAGE_SSH_KEY }}
        source: "./build/*"
        target: "/var/www/html/"
